sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/points
    max_range: 5.0
    point_subsample: 3
    padding_offset: 0.05
    padding_scale: 1.15
    max_update_rate: 10
    filtered_cloud_topic: filtered_cloud
    ns: kinect
